title = "Luau Futures"

[docusaurus]
tagline = "Rust-like futures for Luau"

[home]
enabled = true

[footer]
copyright = "Copyright © 2024 YetAnotherClown. Built with Moonwave and Docusaurus"

[[navbar.items]]
title = "Discord"
href = "https://discord.gg/nKCV5fjEvH"
position = "right"
className = "discord-logo-link"
