name = "yetanotherclown/luau_futures"
version = "0.1.0"
description = "Rust-like futures for Luau"
authors = ["YetAnotherClown"]
repository = "https://github.com/YetAnotherClown/luau-futures"
license = "MIT"

[target]
environment = "luau"
lib = "src"

[indices]
default = "https://github.com/daimond113/pesde-index"
