name = "yetanotherclown/luau_futures"
version = "2.0.0-beta.2"
description = "Rust-like futures for Luau"
authors = ["YetAnotherClown"]
repository = "https://github.com/YetAnotherClown/luau-futures"
license = "MIT"
includes = [
    "!src/__*__",
    "!src/__*__/*",
    "!src/jest.config.luau",
    "src",
    "pesde.lock",
    "README.md",
]

[target]
environment = "luau"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/daimond113/pesde-index"
