[package]
name = "clownxz/future"
description = "A Minimal, Typed Future Implementation inspired by the concept of Futures from the Rust Ecosystem."
version = "1.0.0"
license = "MIT"
authors = ["Clownxz"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["lib", "lib/*", "default.project.json", "wally.toml", "wally.lock"]

[dependencies]
ThreadPool = "clownxz/threadpool@1.0.0"
